# YAML Anchors
x-common-env: &common-env
  DB_HOSTS: postgres,postgres2             # Required STRING (none). Hostname of PostgreSQL-DB. Format: <string>
  DB_USER: postgres             # Required STRING (postgres). Username for target database. Format: <string>
  DB_PASSWORD: postgres         # Required STRING (postgres). Password for target database. Format: <string>
  DB_NAME: scalability          # Required STRING (scalability). Name of the target database. Format: <string>
  REDIS_HOST: redis             # Required STRING (none). Hostname of Redis-Servers for the task-queue. Format: <string>

  REDIS_PORT: 6379              # Optional INTEGER (6379). Port of the Redis-Server. Format: <integer>
  REDIS_QUEUE_NAME: image_tasks # Optional STRING (image_tasks). Queue-name in redis. Format: <string>

x-api-env: &api-env
  <<: *common-env
  # optional but recommended to adjust to your system for performance
  MAX_API_CAPACITY: 50      # Optional INTEGER (50). Maximal amount of concurrent requests one API-Instance should handle. Format: <integer>
  DB_MAX_CONN: 20           # Optional INTEGER (20). Maximum number of open DB connections in the pool (best practice: less than MAX_API_CAPACITY). Format: <integer>
  MAX_GLOBAL_QUEUE_SIZE: 30 # Optional INTEGER (30). Global queue-capacity of entire cluster  (Little's Law: Max_Age_In_Queue * #Workers * Throughput). <integer>
                            # e.g.: 30 = 15s * (1 * 2/s)        (Workers process approx. 2 images/sec, including downloading and classification)

# Services
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres     # Required STRING (postgres). Initial superuser-name for the DB. Format: <string>
      POSTGRES_PASSWORD: postgres # Required STRING (postgres). Initial password for superuser. Format: <string>
      POSTGRES_DB: scalability    # Required STRING (scalability). Initial name of PostgreSQL-DB. Format: <string>
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  postgres2:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres     # Required STRING (postgres). Initial superuser-name for the DB. Format: <string>
      POSTGRES_PASSWORD: postgres # Required STRING (postgres). Initial password for superuser. Format: <string>
      POSTGRES_DB: scalability    # Required STRING (scalability). Initial name of PostgreSQL-DB. Format: <string>
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-1:
    build: 
      context: ./api
    environment:
      <<: *api-env
    depends_on:
      - redis
      - postgres
      - postgres2

  api-2:
    build: 
      context: ./api
    environment:
      <<: *api-env
    depends_on:
      - redis
      - postgres
      - postgres2

  worker:
    build: 
      context: ./worker
    environment:
      <<: *common-env
      MAX_QUEUE_AGE_SECONDS: 15 # Optional INTEGER (15). Maximum amount of time a task can remain in the queue. Format: <integer>
    depends_on:
      - redis
      - postgres
      - postgres2

  loadbalancer:
    image: nginx:1.31.1
    ports:
      - "8001:8000"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2